### ISSUE TITLE
Memory exhaustion on the gateway node (node-2)

### ISSUE THREAD

**Issue by 0rky** [tntech-ngin/ndn-hydra#1]
Hello,

I am trying to use the hydra packages, but I ran into some problems, I hope the authors will be able to solve my issue. 

I am able to recreate the issue. The conditions are as follows:

Ndn_hydra version: 0.3.15

Created a file of size 2GB.
Insert the file: ndn-hydra-client insert -r /hydra -f /2gb_file -p 2gb_file
After the insertion is done check the RAM (memory) usage of node-2 (gateway node) it is above 2.7GB.

Insert the same file again with a different name: ndn-hydra-client insert -r /hydra -f /2gb_file_1 -p 2gb_file
After the insertion is done checked the RAM (memory) usage of node-2 (gateway node) it is above 4.7GB.

The node-2 is having a RAM size of 8Gb, So If I try two more times the memory becomes overburdened and the application will not work. 

The RAM is not getting cleared. It keeps on accumulating the files(data) which is the issue.

I hope this issue gets resolved. Happy to help with any further questions.

**Comment by sankalpatimilsina12** [comment]
@0rky,

Just to confirm, was the application tested until it exhausted all resources and stopped working?

**Comment by tntech-ngin** [comment]
This is fixed and merged as PR 14.
