### ISSUE TITLE
Insert.py get rid of -w flag

### ISSUE THREAD

**Issue by tntech-ngin** [tntech-ngin/ndn-hydra#12]
Insert.py get rid of -w flag

**Comment by tntech-ngin** [comment]
@sankalpatimilsina12 @GportDev Was this merged? I remember discussing this but don't remeber the resolution.

**Comment by GportDev** [comment]
I think it was. The -w flag is working as expected

**Comment by tntech-ngin** [comment]
Expected outcome - client uploads to one node (e.g., node5). After insertion, node5 notifies others. The other nodes get the data from node5 and not from the client.
