### ISSUE TITLE
Favor value does restore when the file delete from Hydra node 

### ISSUE THREAD

**Issue by xai990** [tntech-ngin/ndn-hydra#48]
Hello, 
The delete command cannot restore the favor value to its original value.
When I insert large files to Hydra, the favor value of nodes decrease to 12 from 13 (-1). However, as I deleted all  files from Hydra, the favor value of Hydra nodes was kept at 12.

**Comment by GportDev** [comment]
One possible reason can be that the files are being deleted from Hydra but not from the node, causing the remaining space at the node to stay the same, which leads to the same favor value
