### ISSUE TITLE
[Urgent] Improve fetch performance

### ISSUE THREAD

**Issue by tntech-ngin** [tntech-ngin/ndn-hydra#52]
We can bring the whole set of packets into memory when the first request comes in.
When the last segment is requested, we free the memory.
We can also keep a counter of last request and decide when it is time to delete it from memory.

This changes will need to happen somewhere around here:
https://github.com/tntech-ngin/ndn-hydra/blob/54157d313c3c20f0ccb794fe413d4c852fb650a2/ndn_hydra/repo/handles/read_handle.py#L101

**Comment by sankalpatimilsina12** [comment]
@tntech-ngin Sure, thanks for the heads up on this, I can start looking at it.

I am thinking there might be other aspects to this, like serving a single segment, cache misses, etc. I'll try to find an implementation and will let you know as I make progress.

**Comment by tntech-ngin** [comment]
We are going to do the following:

a) Request for segment 0 comes in, check if you have enough free memory
b) If yes, bring in the file into memory
c) If not, serve from DB

**Comment by tntech-ngin** [comment]
Tasks @sankalpatimilsina12 @GportDev 

* SQL query to get all the packets into memory
* Add a new function get_packets()
* Code modification - if you receive the first segment, go through the normal flow. If not, look into the memory object for the segment
* If a memory object/dictionary representing a file has not been used for X seconds, free it.

Please add others.
